# Generated by Selenium IDE
import pandas as pd
import pytest
from datetime import datetime
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = webdriver.Chrome()
  
df = pd.read_excel("testdataWeb2.xlsx")
for index, row in df.iterrows():
      batchval=row["batch"]
      branchval=row["branch"]
      subjectval=row["subject"]
      dateval=row["date"]
      break
 
driver.get("http://localhost/stud-attend/index.php")
driver.set_window_size(1186, 800)
driver.find_element(By.ID, "input1").click()
driver.find_element(By.ID, "input1").send_keys("teacher")
driver.find_element(By.NAME, "pass").click()
driver.find_element(By.NAME, "pass").send_keys("admin")
driver.find_element(By.CSS_SELECTOR, "label:nth-child(2) > #optionsRadios1").click()
driver.find_element(By.NAME, "login").click()
driver.find_element(By.LINK_TEXT, "Attendance").click()
driver.find_element(By.ID, "input1").click()
dropdown = driver.find_element(By.ID, "input1")
dropdown.find_element(By.XPATH, "//option[. = "+str(batchval)+"]").click()
driver.find_element(By.ID, "selectbranch").click()
dropdown = driver.find_element(By.ID, "selectbranch")
dropdown.find_element(By.XPATH, "//option[. = '"+branchval+"']").click()
driver.find_element(By.NAME, "batch").click()
#date
driver.find_element(By.NAME, "attdate").click()
#dateconvert = datetime.strptime(str(dateval), "%Y-%m-%d %H:%M:%S").date()
driver.find_element(By.NAME, "attdate").send_keys(str(dateval.date()))

driver.find_element(By.ID, "sb2").click()
dropdown = driver.find_element(By.ID, "sb2")
dropdown.find_element(By.XPATH, "//option[. = '"+branchval+"']").click()
driver.find_element(By.ID, "sb2").click()
driver.find_element(By.ID, "subject").click()
dropdown = driver.find_element(By.ID, "subject")
dropdown.find_element(By.XPATH, "//option[. = '"+subjectval+"']").click()
i=1
flag=0
for index, row in df.iterrows():
  get_text=driver.find_element(By.CSS_SELECTOR, "tr:nth-child("+str(i)+") td:nth-child(1)").text
  if str(row["studentid"])==str(get_text):
        if row["status"]=="Present":
              driver.find_element(By.CSS_SELECTOR, "tr:nth-child("+str(i)+") input:nth-child(2)").click()
        elif row["status"]=="Absent":
              driver.find_element(By.CSS_SELECTOR, "tr:nth-child("+str(i)+") input:nth-child(4)").click()
        else:
              print("status error")
  else: 
    t1="\Given student ID is not present in the particular batch  --  Test Case failed"
    flag=1
  i+=1
  
  
if flag==0:
      t1="Succesfully Marked all attendance  -- Test case Passed"
ts=datetime.now()
date_time=ts.strftime("%d-%m-%Y, %H:%M:%S")
f = open("testlog2.txt", "a")
f.write("\nTest Case on Attendance")
f.write("\n"+date_time+"   Run 1:"+"\t"+t1)
f.close()

#driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) input:nth-child(4)").click()
#driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) input:nth-child(2)").click()
driver.find_element(By.NAME, "att").click()
driver.close()
  