# Generated by Selenium IDE
import pytest
import time
import json
import pandas as pd
import streamlit as st
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



st.title("Excel Data Analysis")
STIDarr=[]
driver = webdriver.Chrome()
# File uploader widget
uploaded_file = st.file_uploader("Upload Excel file", type=["xlsx"])
if uploaded_file is not None:
  df = pd.read_excel(uploaded_file)
  for index, row in df.iterrows():
      stid=row["studentID"]
      STIDarr.append(stid)
      stname=row["studentName"]
      stdept=row["department"]
      stbatch=row["studentBatch"]
      stsem=row["sem"]
      stemail=row["email"]
      #st.write(stid,stname,stdept,stbatch,stsem,stemail)
      
      if((stdept=="CSE" or stdept=="EC")):
      
        driver.get("http://localhost/stud-attend/index.php")
        driver.set_window_size(1186, 800)
        driver.find_element(By.ID, "input1").click()
        driver.find_element(By.ID, "input1").send_keys("admin")
        driver.find_element(By.NAME, "pass").click()
        driver.find_element(By.NAME, "pass").send_keys("admin")
        driver.find_element(By.CSS_SELECTOR, "label:nth-child(3) > #optionsRadios1").click()
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.ID, "input1").click()
        driver.find_element(By.ID, "input1").send_keys(str(stid))
        driver.find_element(By.NAME, "st_name").click()
        driver.find_element(By.NAME, "st_name").send_keys(str(stname))
        driver.find_element(By.NAME, "st_dept").click()
        driver.find_element(By.NAME, "st_dept").send_keys(str(stdept))
        driver.find_element(By.NAME, "st_batch").click()
        driver.find_element(By.NAME, "st_batch").send_keys(str(stbatch))
        driver.find_element(By.NAME, "st_sem").click()
        driver.find_element(By.NAME, "st_sem").send_keys(str(stsem))
        driver.find_element(By.NAME, "st_email").click()
        driver.find_element(By.NAME, "st_email").send_keys(str(stemail))
        driver.find_element(By.NAME, "std").click()
        st.write("Uploaded Excel Data to DB:")
        st.write(stid,stname,stdept,stbatch,stsem,stemail)

  for x in STIDarr:
        driver.get("http://localhost/stud-attend/admin/deleteStudtest.php?studid="+str(x))
driver.close()


  
